### PR TITLE
protecode: remove image filter

### PR DESCRIPTION
**Pull request by jensh007**
**What this PR does / why we need it**:
Remove image filter from protecode scanning

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Review by ccwienk — CHANGES_REQUESTED** [review]
also rm `ImageFilterMixin` from concourse/model/traits/images.py and usage in ../image_scan.py

**Comment by ccwienk** [comment]
@jensh007 : please check broken unittest(s)

**Comment by jensh007** [comment]
ImageMixinFilter removed

**Comment by jensh007** [comment]
fixed

**Review by AndreasBurger — APPROVED** [review]

**Pull request merged**
