### PR TITLE
Add Release Note Categories

### PR DESCRIPTION
**Pull request by petersutter**
**What this PR does / why we need it**:
With this PR, new release note categories and a new target group will be introduced.

Today we have:
```
Format of block header: <category> <target_group>
Possible values:
- category:       improvement|noteworthy|action
- target_group:   user|operator|developer
```

Which changes to:
```
Format of block header: <category> <target_group>
Possible values:
- category:       breaking|feature|bugfix|doc|other
- target_group:   user|operator|developer|dependency
```

The "old" categories are still kept for compatibility reasons, but can be removed in the future. This is how the old categories are mapped to the new ones:
`improvement` -> `other`
`noteworthy` -> remains as is, but the category title changes from `Most notable changes` to `📰 Noteworthy`
`action` -> `breaking`

As discussed offline with @timebertt, the `dependency` target could be used for the scenario listed in #482
> [...] a dedicated release note type for changes in g/g/ext that affect extension developers and that contain improvements for all extension controllers (e.g. in the generic worker actuator)

The release notes will look like

---

# [dummy-component]
## ⚠️ Breaking Changes
- [DEVELOPER] Allow to specify a custom network in Cluster.Spec (#196 @petersutter)
- ...

## ✨ New Features
- [USER] Allow the ability to configure frontend and backend port for LB (#215 @petersutter)
- ...

## 🐛 Bug Fixes
- [DEVELOPER] Support running alongside other Cluster API pods in the same namespace with leader election enabled (#211 @petersutter)
- ...

## 📖 Documentation
- [DEVELOPER] Dev oriented doc for the conformance tests (#208 @petersutter)
- ...

## 🏃 Others
- [DEVELOPER] Go mod files and generated files (#212 @petersutter)
- ...

---

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by rfranzke** [comment]
Love it

**Comment by timebertt** [comment]
Thanks a lot @petersutter, I like it too :)

**Review by ccwienk — APPROVED** [review]
hi @petersutter : sorry for taking so long (I have to filter-out all gh-emails / did not yet find the time to configure better filtering rules)

lgtm - did not test it, though :-)

**Pull request merged**
