### PR TITLE
Remove bdba scan from pipeline template

### PR DESCRIPTION
**Pull request by 8R0WNI3**
**What this PR does / why we need it**:
As a restructuring, the compliance scanning tools shall be moved to standalone kubernetes deployments instead of running as a pipeline job. These kubernetes deployments will be part of the so-called delivery-gear.
As a first step, the BDBA compliance scan for vulnerabilities and licenses as well as the replication of the compliance-tracking-issues were included in the delivery-gear recently. So, this pipeline template is not required anymore.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by ccwienk** [comment]
@8R0WNI3 which usages are missing?

**Comment by 8R0WNI3** [comment]
@ccwienk the landscaper-live repository still has an open PR to remove bdba from the scan job

**Review by ccwienk — CHANGES_REQUESTED** [review]
two remarks:
- should also include concourse/steps/scan_container_images.py
- this will also remove malware-scanning, will it not? -> we need to migrate malware-scanning into a standalone extension, too (prior to removing from template)

**Pull request merged**
